################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
driverlib/driverlib/MSP430F5xx_6xx/adc10_a.obj: ../driverlib/driverlib/MSP430F5xx_6xx/adc10_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/adc10_a.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/adc12_a.obj: ../driverlib/driverlib/MSP430F5xx_6xx/adc12_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/adc12_a.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/aes.obj: ../driverlib/driverlib/MSP430F5xx_6xx/aes.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/aes.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/battbak.obj: ../driverlib/driverlib/MSP430F5xx_6xx/battbak.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/battbak.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/comp_b.obj: ../driverlib/driverlib/MSP430F5xx_6xx/comp_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/comp_b.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/crc.obj: ../driverlib/driverlib/MSP430F5xx_6xx/crc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/crc.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/ctsd16.obj: ../driverlib/driverlib/MSP430F5xx_6xx/ctsd16.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/ctsd16.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/dac12_a.obj: ../driverlib/driverlib/MSP430F5xx_6xx/dac12_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/dac12_a.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/dma.obj: ../driverlib/driverlib/MSP430F5xx_6xx/dma.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/dma.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/eusci_a_spi.obj: ../driverlib/driverlib/MSP430F5xx_6xx/eusci_a_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/eusci_a_spi.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/eusci_a_uart.obj: ../driverlib/driverlib/MSP430F5xx_6xx/eusci_a_uart.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/eusci_a_uart.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/eusci_b_i2c.obj: ../driverlib/driverlib/MSP430F5xx_6xx/eusci_b_i2c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/eusci_b_i2c.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/eusci_b_spi.obj: ../driverlib/driverlib/MSP430F5xx_6xx/eusci_b_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/eusci_b_spi.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/flashctl.obj: ../driverlib/driverlib/MSP430F5xx_6xx/flashctl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/flashctl.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/gpio.obj: ../driverlib/driverlib/MSP430F5xx_6xx/gpio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/gpio.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/lcd_b.obj: ../driverlib/driverlib/MSP430F5xx_6xx/lcd_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/lcd_b.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/ldopwr.obj: ../driverlib/driverlib/MSP430F5xx_6xx/ldopwr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/ldopwr.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/mpy32.obj: ../driverlib/driverlib/MSP430F5xx_6xx/mpy32.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/mpy32.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/oa.obj: ../driverlib/driverlib/MSP430F5xx_6xx/oa.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/oa.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/pmap.obj: ../driverlib/driverlib/MSP430F5xx_6xx/pmap.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/pmap.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/pmm.obj: ../driverlib/driverlib/MSP430F5xx_6xx/pmm.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/pmm.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/ram.obj: ../driverlib/driverlib/MSP430F5xx_6xx/ram.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/ram.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/ref.obj: ../driverlib/driverlib/MSP430F5xx_6xx/ref.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/ref.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/rtc_a.obj: ../driverlib/driverlib/MSP430F5xx_6xx/rtc_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/rtc_a.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/rtc_b.obj: ../driverlib/driverlib/MSP430F5xx_6xx/rtc_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/rtc_b.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/rtc_c.obj: ../driverlib/driverlib/MSP430F5xx_6xx/rtc_c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/rtc_c.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/sd24_b.obj: ../driverlib/driverlib/MSP430F5xx_6xx/sd24_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/sd24_b.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/sfr.obj: ../driverlib/driverlib/MSP430F5xx_6xx/sfr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/sfr.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/sysctl.obj: ../driverlib/driverlib/MSP430F5xx_6xx/sysctl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/sysctl.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/tec.obj: ../driverlib/driverlib/MSP430F5xx_6xx/tec.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/tec.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/timer_a.obj: ../driverlib/driverlib/MSP430F5xx_6xx/timer_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/timer_a.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/timer_b.obj: ../driverlib/driverlib/MSP430F5xx_6xx/timer_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/timer_b.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/timer_d.obj: ../driverlib/driverlib/MSP430F5xx_6xx/timer_d.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/timer_d.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/tlv.obj: ../driverlib/driverlib/MSP430F5xx_6xx/tlv.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/tlv.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/ucs.obj: ../driverlib/driverlib/MSP430F5xx_6xx/ucs.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/ucs.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/usci_a_spi.obj: ../driverlib/driverlib/MSP430F5xx_6xx/usci_a_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/usci_a_spi.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/usci_a_uart.obj: ../driverlib/driverlib/MSP430F5xx_6xx/usci_a_uart.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/usci_a_uart.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/usci_b_i2c.obj: ../driverlib/driverlib/MSP430F5xx_6xx/usci_b_i2c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/usci_b_i2c.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/usci_b_spi.obj: ../driverlib/driverlib/MSP430F5xx_6xx/usci_b_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/usci_b_spi.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/driverlib/MSP430F5xx_6xx/wdt_a.obj: ../driverlib/driverlib/MSP430F5xx_6xx/wdt_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=eabi --data_model=restricted -O2 --opt_for_speed=0 --use_hw_mpy=F5 --include_path="C:/TI/ccsv6/ccs_base/msp430/include" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/apps" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/aes" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/bsp" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/hostcmd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/lcd" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/common" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/devices/cc112x" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/interrupt" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/nvm" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/radio" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/targets/trxeb_msp430f5438a" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/components/timer" --include_path="C:/Users/Administrator/Documents/CCS Projects/DOOR SENSOR V2/sigfox_library_api" --include_path="C:/TI/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --advice:power="all" -g --define=DOWNLINK --define=__MSP430F5438A__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="driverlib/driverlib/MSP430F5xx_6xx/wdt_a.pp" --obj_directory="driverlib/driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


